utc: "2020-10-29 0:05:00 -0500" #Required. The start time of the event. Best to use UTC format, but may work in other date formats too.
name: " " #Required. The human-readable name of the event
logo: "https://raw.githubusercontent.com/CyberSEEC/test/main/assets/img/CyberSEEC-logo.png" #Required. logo for the event. replace this logo in the project or add a new file and change the value of this variable
description: "CyberSEEC will be a great event. Get excited!" #Required. short description of the event. this is used in the preview when the link is shared on facebook
externalLink: "https://www.cooperative.com/conferences-education/web-based-learning/2020-cyberseec/Pages/default.aspx" #Required. link to the main event page. this could be a webpage, a facebook event, an eventbrite page, where ever the main webpage is for your event
url: "http://countdown.yourdomain.com" #(Optional) the full URL for this countdown page. This is neccesary for facebook share previews
facebookEventLink: "https://www.cooperative.com/my-account/pages/public-registration.aspx?eventkey=e419f040-208f-4bbe-946c-68074212d1a5" #(Optional) if you have a facebook event, put the link here and we'll add a "RSVP on facebook" link at the bottom.
hashtag: "" #(Optional) hashtag for the event, example "#hashtag". must be in quotes.
colors: #(Optional)
  background: "#FFF" #color of the background of the page
  primary: "#3FBFBC" #primary color for the page
  secondary: "#EE4823" #secondary color for the page
  textcolor: "#FFF" #color of the text, which is overlayed on the primary color
fontfamily: "'Open Sans', sans-serif" #optional

theme: jekyll-theme-tactile
